canal:
  server: 192.168.0.8:11111
  destination: example
spring:
  application:
    name: canal-example
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.8:3306/ipas-system
    username: haoyu
    password: 888888
  jooq:
    sql-dialect: mysql
  flyway:
    baseline-on-migrate: true